version: "2.1"

services:
  # https://hub.docker.com/r/_/nginx
  web:
    image: nginx:1.21.4-alpine

  dnat:
    build: dnat
    labels:
      io.balena.features.balena-socket: 1
    environment:
      FORWARD_SERVICE: web
      FORWARD_PORT: 80
      FORWARD_PROTOCOLS: tcp
    depends_on:
      - web
